/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send chat message and receive streaming AI response
         * @description Sends a user message to the AI therapist and receives a streaming response.
         *     The response is delivered as Server-Sent Events (SSE) for real-time interaction.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatRequest"];
                };
            };
            responses: {
                /** @description Streaming chat response */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        "X-Model-Id": components["headers"]["X-Model-Id"];
                        "X-Tool-Choice": components["headers"]["X-Tool-Choice"];
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve all chat sessions
         * @description Gets a cursor-paginated list of chat sessions with message counts and metadata.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of sessions to return (default 50) */
                    limit?: number;
                    /** @description Cursor from a previous response to request the next page */
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cursor-paginated list of sessions */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["SessionsListData"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /**
         * Create a new chat session
         * @description Creates a new therapeutic chat session with a specified title
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSessionRequest"];
                };
            };
            responses: {
                /** @description Created session */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Session"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current active session
         * @description Returns the most recently updated active session for the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current active session (if any) */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                currentSession?: components["schemas"]["Session"] | null;
                            };
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /**
         * Set current active session
         * @description Sets the authenticated user's current session pointer without mutating session lifecycle state.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Convex session document identifier */
                        sessionId: string;
                    };
                };
            };
            responses: {
                /** @description Current session pointer updated */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                /** @example true */
                                success?: boolean;
                                session?: components["schemas"]["Session"];
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Session not found or access denied */
                404: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        /**
         * Clear current active session
         * @description Clears the authenticated user's current session pointer.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current session pointer cleared */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                /** @example true */
                                success?: boolean;
                            };
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get session details
         * @description Retrieves a session and associated messages/reports for the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session details */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Session not found */
                404: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a chat session
         * @description Permanently deletes a chat session and all associated messages
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description UUID of the session to delete
                     * @example 123e4567-e89b-12d3-a456-426614174000
                     */
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session deleted successfully */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Session deleted successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update session
         * @description Updates title, status, or endedAt on an existing session.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                        status?: string;
                        /** Format: date-time */
                        endedAt?: string | null;
                    };
                };
            };
            responses: {
                /** @description Session updated */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                /** @description Session not found */
                404: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        trace?: never;
    };
    "/sessions/{sessionId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume a completed session
         * @description Explicit lifecycle command that sets the specified session back to active and sets the current session pointer.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session resumed */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Session"];
                        };
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List messages for a session
         * @description Retrieves messages for the specified session with pagination
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default 1) */
                    page?: number;
                    /** @description Page size (default 50, max 100) */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description UUID of the session */
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of messages */
                200: {
                    headers: {
                        /** @description Correlation ID for tracing this request */
                        "X-Request-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                items?: components["schemas"]["Message"][];
                                pagination?: {
                                    page?: number;
                                    limit?: number;
                                    total?: number;
                                    totalPages?: number;
                                    hasNext?: boolean;
                                    hasPrev?: boolean;
                                };
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /**
         * Save a message to a session
         * @description Saves a user or assistant message to the specified session
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID of the session */
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewMessage"];
                };
            };
            responses: {
                /** @description Message saved successfully */
                200: {
                    headers: {
                        /** @description Correlation ID for tracing this request */
                        "X-Request-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Message"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/messages/{messageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update message metadata
         * @description Updates metadata for a specific message in a session.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                    messageId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        metadata?: {
                            [key: string]: unknown;
                        };
                        /** @enum {string} */
                        mergeStrategy?: "merge" | "replace";
                    };
                };
            };
            responses: {
                /** @description Message metadata updated */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Message"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List generated reports
         * @description Retrieves generated session reports for the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reports list */
                200: {
                    headers: {
                        /** @description Correlation ID for tracing this request */
                        "X-Request-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["SessionReport"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate session report (detailed)
         * @description Generates a therapeutic report from server-side session history and returns the raw report content.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        sessionId: string;
                        /** @description Optional model override */
                        model?: string;
                    };
                };
            };
            responses: {
                /** @description Generated report content */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                reportContent?: string;
                                modelUsed?: string;
                                modelDisplayName?: string;
                                cbtDataSource?: string;
                                cbtDataAvailable?: boolean;
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Session has no reportable messages */
                422: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/generate-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate session report from provided context
         * @description Generates a therapeutic report using authenticated session ownership and caller-provided contextual messages.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        sessionId: string;
                        contextualMessages: {
                            /** @enum {string} */
                            role: "user" | "assistant";
                            content: string;
                            /** Format: date-time */
                            timestamp?: string;
                        }[];
                        /** @description Optional model override */
                        model?: string;
                    };
                };
            };
            responses: {
                /** @description Generated report content */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                reportContent?: string;
                                modelUsed?: string;
                                modelDisplayName?: string;
                                cbtDataSource?: string;
                                cbtDataAvailable?: boolean;
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Session not found or access denied */
                404: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Session has no reportable messages */
                422: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve memory context reports
         * @description Returns recent reports for cross-session therapeutic memory.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    excludeSessionId?: string;
                    manage?: boolean;
                    includeFullContent?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Memory context response */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["MemoryData"] | components["schemas"]["MemoryManageData"];
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete memory context reports
         * @description Deletes reports from memory context with filtering options.
         */
        delete: {
            parameters: {
                query?: {
                    limit?: number;
                    excludeSessionId?: string;
                    sessionIds?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Memory deletion response */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["DeleteResponseData"];
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available AI models
         * @description Retrieves a list of available AI models configured in the application (Groq defaults
         *     and optional local Ollama). Includes token limits and categorization (featured, production).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of available models */
                200: {
                    headers: {
                        /** @description Correlation ID for tracing this request */
                        "X-Request-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            models?: components["schemas"]["ModelConfig"][];
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/env": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check environment configuration
         * @description Checks if required environment variables are configured, particularly
         *     the Groq API key. Used by the frontend to determine UI behavior.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Environment status */
                200: {
                    headers: {
                        /** @description Correlation ID for tracing this request */
                        "X-Request-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Whether GROQ_API_KEY environment variable is set
                             * @example true
                             */
                            hasGroqApiKey?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Error endpoint status
         * @description Returns a lightweight status response for client error reporting endpoint checks.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Endpoint status */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                /** Format: date-time */
                                timestamp?: string;
                                /** @example ok */
                                status?: string;
                            };
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /**
         * Report client-side error
         * @description Receives client error reports (message, stack) and logs them with request context. Returns standardized success response.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        error?: string;
                        stack?: string;
                        componentStack?: string;
                    };
                };
            };
            responses: {
                /** @description Error logged successfully */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                /** @example Error logged successfully */
                                message?: string;
                            };
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Message: {
            /**
             * Format: uuid
             * @description Unique identifier for the message
             * @example msg-123e4567-e89b-12d3-a456-426614174000
             */
            id?: string;
            /**
             * @description The role of the message sender
             * @enum {string}
             */
            role: "user" | "assistant";
            /**
             * @description The message content
             * @example I'm struggling with anxiety and need some guidance
             */
            content: string;
            /**
             * Format: date-time
             * @description When the message was created
             */
            timestamp?: string;
            /**
             * Format: date-time
             * @description Database creation timestamp
             */
            createdAt?: string;
        };
        NewMessage: {
            /**
             * @description The role of the message sender
             * @enum {string}
             */
            role: "user" | "assistant";
            /** @description The message content */
            content: string;
            /** @description Optional model identifier used for assistant messages */
            modelUsed?: string;
        };
        Session: {
            /**
             * @description Unique session identifier (Convex document ID)
             * @example j57d6p8h9n2x3q4r5s6t7u8v9w
             */
            id: string;
            /**
             * @description Canonical authenticated user identifier (Clerk user ID)
             * @example user_2xYzAbCdEfGhIjKl
             */
            userId: string;
            /**
             * @description Human-readable session title
             * @example Managing Work Stress
             */
            title: string;
            /**
             * @description Current session status
             * @enum {string}
             */
            status: "active" | "completed";
            /**
             * Format: date-time
             * @description When the session was started
             */
            startedAt?: string;
            /**
             * Format: date-time
             * @description When the session was completed
             */
            endedAt?: string | null;
            /**
             * Format: date-time
             * @description Database creation timestamp
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Database update timestamp
             */
            updatedAt?: string;
            _count?: {
                /**
                 * @description Number of messages in this session
                 * @example 12
                 */
                messages?: number;
            };
        };
        SessionsPagination: {
            /**
             * @description Maximum number of sessions requested for this page
             * @example 50
             */
            limit: number;
            /**
             * @description Total number of sessions available for the authenticated user
             * @example 128
             */
            total: number;
            /**
             * @description Whether there is another page after this response
             * @example true
             */
            hasMore: boolean;
            /**
             * @description Cursor to request the next page, null when no additional pages exist
             * @example session_cursor_eyJpZCI6InNlc3Npb24ifQ
             */
            nextCursor: string | null;
        };
        SessionsListData: {
            items: components["schemas"]["Session"][];
            pagination: components["schemas"]["SessionsPagination"];
        };
        SessionReport: {
            /**
             * Format: uuid
             * @description Unique report identifier
             */
            id: string;
            /**
             * Format: uuid
             * @description Associated session ID
             */
            sessionId: string;
            /** @description JSON string of key discussion points */
            keyPoints?: string;
            /** @description AI-generated therapeutic analysis */
            therapeuticInsights: string;
            /** @description JSON string of identified behavioral patterns */
            patternsIdentified?: string;
            /** @description JSON string of recommended actions */
            actionItems?: string;
            /** @description Overall mood assessment */
            moodAssessment?: string | null;
            /** @description Progress tracking notes */
            progressNotes?: string | null;
            /**
             * Format: date-time
             * @description Report generation timestamp
             */
            createdAt?: string;
        };
        MemoryContextEntry: {
            sessionTitle: string;
            /** Format: date */
            sessionDate: string;
            /** Format: date */
            reportDate: string;
            content: string;
            summary: string;
        };
        MemoryStats: {
            totalReportsFound: number;
            successfullyDecrypted: number;
            failedDecryptions: number;
        };
        MemoryData: {
            memoryContext: components["schemas"]["MemoryContextEntry"][];
            reportCount: number;
            stats: components["schemas"]["MemoryStats"];
        };
        MemoryReportDetail: {
            id: string;
            sessionId: string;
            sessionTitle: string;
            /** Format: date */
            sessionDate: string;
            /** Format: date */
            reportDate: string;
            contentPreview: string;
            keyInsights: string[];
            hasEncryptedContent: boolean;
            reportSize: number;
            fullContent?: string;
            structuredCBTData?: {
                [key: string]: unknown;
            };
        };
        MemoryManagementStats: {
            totalReportsFound: number;
            successfullyProcessed: number;
            failedDecryptions: number;
            hasMemory: boolean;
        };
        MemoryManageData: {
            memoryDetails: components["schemas"]["MemoryReportDetail"][];
            reportCount: number;
            stats: components["schemas"]["MemoryManagementStats"];
        };
        DeleteResponseData: {
            deletedCount: number;
            message: string;
            /** @enum {string} */
            deletionType: "specific" | "recent" | "all-except-current" | "all";
        };
        ModelConfig: {
            /**
             * @description Model identifier used in API calls
             * @example openai/gpt-oss-120b
             */
            id: string;
            /**
             * @description Human-readable model name
             * @example GPT OSS 120B
             */
            name: string;
            /**
             * @description Model provider/company
             * @example OpenAI
             */
            provider: string;
            /**
             * @description Maximum tokens supported by the model
             * @example 32000
             */
            maxTokens: number;
            /**
             * @description Model category/stability level
             * @example featured
             * @enum {string}
             */
            category: "featured" | "production" | "preview";
        };
        ChatRequest: {
            /** @description Array of conversation messages */
            messages: {
                /** @enum {string} */
                role?: "user" | "assistant";
                content?: string;
            }[];
            /**
             * Format: uuid
             * @description Optional session ID for context
             */
            sessionId?: string;
            /**
             * @description AI model to use
             * @example openai/gpt-oss-120b
             */
            model?: string;
            /** @description Groq API key (if not set in environment) */
            apiKey?: string;
            /**
             * @description Response creativity (0=focused, 2=creative)
             * @example 0.7
             */
            temperature?: number;
            /**
             * @description Maximum response length
             * @example 2000
             */
            maxTokens?: number;
            /**
             * @description Nucleus sampling parameter
             * @example 0.9
             */
            topP?: number;
        };
        CreateSessionRequest: {
            /**
             * @description Session title
             * @example Managing Anxiety and Stress
             */
            title: string;
        };
        EmailReportRequest: {
            /**
             * Format: uuid
             * @description Session to generate report for
             */
            sessionId: string;
            /** @description Session messages */
            messages: components["schemas"]["Message"][];
            /**
             * Format: email
             * @description Recipient email address
             * @example user@example.com
             */
            emailAddress: string;
            /**
             * @description AI model for report generation
             * @example openai/gpt-oss-120b
             */
            model?: string;
            emailConfig?: {
                /**
                 * @description Email service type
                 * @enum {string}
                 */
                service?: "console" | "smtp";
                /**
                 * @description SMTP server hostname
                 * @example smtp.gmail.com
                 */
                smtpHost?: string;
                /**
                 * Format: email
                 * @description SMTP username
                 */
                smtpUser?: string;
                /** @description SMTP password or app password */
                smtpPass?: string;
                /**
                 * Format: email
                 * @description Sender email address
                 */
                fromEmail?: string;
            };
        };
        Error: {
            /**
             * @description Error message
             * @example Validation failed
             */
            error: string;
            /**
             * @description Detailed error information
             * @example Invalid email address format
             */
            details?: string;
            /**
             * @description Error code for programmatic handling
             * @example VALIDATION_ERROR
             */
            code?: string;
            /**
             * @description Suggested action to resolve the error
             * @example Please check your input and try again
             */
            suggestedAction?: string;
        };
    };
    responses: {
        /** @description Bad request - invalid input */
        BadRequest: {
            headers: {
                /** @description Correlation ID for tracing this request */
                "X-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                /** @description Correlation ID for tracing this request */
                "X-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Correlation ID for tracing this request */
        "X-Request-Id": string;
        /** @description Model identifier used to generate the response */
        "X-Model-Id": string;
        /** @description Tool choice directive for the model (e.g., required/none) */
        "X-Tool-Choice": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
