/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send chat message and receive streaming AI response
         * @description Sends a user message to the AI therapist and receives a streaming response.
         *     The response is delivered as Server-Sent Events (SSE) for real-time interaction.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatRequest"];
                };
            };
            responses: {
                /** @description Streaming chat response */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        "X-Model-Id": components["headers"]["X-Model-Id"];
                        "X-Tool-Choice": components["headers"]["X-Tool-Choice"];
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve all chat sessions
         * @description Gets a list of all chat sessions with message counts and metadata
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of sessions */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Session"][];
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /**
         * Create a new chat session
         * @description Creates a new therapeutic chat session with a specified title
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSessionRequest"];
                };
            };
            responses: {
                /** @description Created session */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Session"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current active session
         * @description Returns the most recently updated active session for the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current active session (if any) */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                currentSession?: components["schemas"]["Session"] | null;
                            };
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /**
         * Set current active session
         * @description Marks the specified session as current by updating its updatedAt and status to active.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        sessionId: string;
                    };
                };
            };
            responses: {
                /** @description Session marked as current */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Session not found or access denied */
                404: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a chat session
         * @description Permanently deletes a chat session and all associated messages
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description UUID of the session to delete
                     * @example 123e4567-e89b-12d3-a456-426614174000
                     */
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session deleted successfully */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Session deleted successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List messages for a session
         * @description Retrieves messages for the specified session with pagination
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default 1) */
                    page?: number;
                    /** @description Page size (default 50, max 100) */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description UUID of the session */
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of messages */
                200: {
                    headers: {
                        /** @description Correlation ID for tracing this request */
                        "X-Request-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                items?: components["schemas"]["Message"][];
                                pagination?: {
                                    page?: number;
                                    limit?: number;
                                    total?: number;
                                    totalPages?: number;
                                    hasNext?: boolean;
                                    hasPrev?: boolean;
                                };
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /**
         * Save a message to a session
         * @description Saves a user or assistant message to the specified session
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description UUID of the session */
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NewMessage"];
                };
            };
            responses: {
                /** @description Message saved successfully */
                200: {
                    headers: {
                        /** @description Correlation ID for tracing this request */
                        "X-Request-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Message"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate session report
         * @description Generates a therapeutic analysis report for a completed session using AI.
         *     The report includes key insights, patterns, and recommendations.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description UUID of the session
                         */
                        sessionId: string;
                        /** @description Array of messages from the session */
                        messages: components["schemas"]["Message"][];
                    };
                };
            };
            responses: {
                /** @description Generated report */
                200: {
                    headers: {
                        /** @description Correlation ID for tracing this request */
                        "X-Request-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionReport"];
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate and email session report
         * @description Generates a therapeutic session report and sends it via email in HTML format.
         *     Supports multiple email service configurations including SMTP and console logging.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmailReportRequest"];
                };
            };
            responses: {
                /** @description Report sent successfully */
                200: {
                    headers: {
                        /** @description Correlation ID for tracing this request */
                        "X-Request-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Report generated and sent successfully */
                            message?: string;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate session report (detailed)
         * @description Generates a therapeutic report from session messages and returns the raw report content.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        sessionId: string;
                        messages: {
                            /** @enum {string} */
                            role?: "user" | "assistant";
                            content?: string;
                            /** Format: date-time */
                            timestamp?: string;
                        }[];
                        /** @description Optional model override */
                        model?: string;
                    };
                };
            };
            responses: {
                /** @description Generated report content */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                reportContent?: string;
                                modelUsed?: string;
                                modelDisplayName?: string;
                                cbtDataSource?: string;
                                cbtDataAvailable?: boolean;
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available AI models
         * @description Retrieves a list of available AI models configured in the application (Groq defaults
         *     and optional local Ollama). Includes token limits and categorization (featured, production).
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of available models */
                200: {
                    headers: {
                        /** @description Correlation ID for tracing this request */
                        "X-Request-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            models?: components["schemas"]["ModelConfig"][];
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/env": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check environment configuration
         * @description Checks if required environment variables are configured, particularly
         *     the Groq API key. Used by the frontend to determine UI behavior.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Environment status */
                200: {
                    headers: {
                        /** @description Correlation ID for tracing this request */
                        "X-Request-Id"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Whether GROQ_API_KEY environment variable is set
                             * @example true
                             */
                            hasGroqApiKey?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report client-side error
         * @description Receives client error reports (message, stack) and logs them with request context. Returns standardized success response.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        error?: string;
                        stack?: string;
                        componentStack?: string;
                    };
                };
            };
            responses: {
                /** @description Error logged successfully */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                /** @example Error logged successfully */
                                message?: string;
                            };
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout and revoke session
         * @description Revokes the current auth session and clears the auth cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout successful */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check session status
         * @description Returns whether the client is authenticated and whether TOTP setup/verification are needed.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session status */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                isAuthenticated?: boolean;
                                needsSetup?: boolean;
                                needsVerification?: boolean;
                            };
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Revoke current session (logout)
         * @description Deletes current session and clears the cookie.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trusted devices and backup codes count */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Device list and backup code info */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                devices?: Record<string, never>[];
                                backupCodesCount?: number;
                            };
                        };
                    };
                };
                401: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /**
         * Device management operation (disabled)
         * @description For security, device management mutations are restricted. Returns a standardized error.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                400: components["responses"]["BadRequest"];
            };
        };
        /** Revoke a trusted device */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        deviceId: string;
                    };
                };
            };
            responses: {
                /** @description Device revoked */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * TOTP diagnostics
         * @description Returns server time and current token for diagnostics (development/support tooling).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Diagnostic data */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                serverTime?: string;
                                serverTimestamp?: number;
                                currentValidToken?: string;
                            };
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Validate a specific token in diagnostics mode */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            responses: {
                /** @description Validation result */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                providedTokenValid?: boolean;
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mobile-debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mobile debugging info
         * @description Returns network, device, and TOTP setup status for mobile debugging.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Debug info */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: Record<string, never>;
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Validate token with client time for mobile debugging */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token?: string;
                        clientTime?: number;
                    };
                };
            };
            responses: {
                /** @description Debug result */
                200: {
                    headers: {
                        "X-Request-Id": components["headers"]["X-Request-Id"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: Record<string, never>;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Message: {
            /**
             * Format: uuid
             * @description Unique identifier for the message
             * @example msg-123e4567-e89b-12d3-a456-426614174000
             */
            id?: string;
            /**
             * @description The role of the message sender
             * @enum {string}
             */
            role: "user" | "assistant";
            /**
             * @description The message content
             * @example I'm struggling with anxiety and need some guidance
             */
            content: string;
            /**
             * Format: date-time
             * @description When the message was created
             */
            timestamp?: string;
            /**
             * Format: date-time
             * @description Database creation timestamp
             */
            createdAt?: string;
        };
        NewMessage: {
            /**
             * @description The role of the message sender
             * @enum {string}
             */
            role: "user" | "assistant";
            /** @description The message content */
            content: string;
            /** @description Optional model identifier used for assistant messages */
            modelUsed?: string;
        };
        Session: {
            /**
             * Format: uuid
             * @description Unique session identifier
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description User identifier (currently uses default user)
             * @example default-user-id
             */
            userId: string;
            /**
             * @description Human-readable session title
             * @example Managing Work Stress
             */
            title: string;
            /**
             * @description Current session status
             * @enum {string}
             */
            status: "active" | "completed";
            /**
             * Format: date-time
             * @description When the session was started
             */
            startedAt?: string;
            /**
             * Format: date-time
             * @description When the session was completed
             */
            endedAt?: string | null;
            /**
             * Format: date-time
             * @description Database creation timestamp
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Database update timestamp
             */
            updatedAt?: string;
            _count?: {
                /**
                 * @description Number of messages in this session
                 * @example 12
                 */
                messages?: number;
            };
        };
        SessionReport: {
            /**
             * Format: uuid
             * @description Unique report identifier
             */
            id: string;
            /**
             * Format: uuid
             * @description Associated session ID
             */
            sessionId: string;
            /** @description JSON string of key discussion points */
            keyPoints?: string;
            /** @description AI-generated therapeutic analysis */
            therapeuticInsights: string;
            /** @description JSON string of identified behavioral patterns */
            patternsIdentified?: string;
            /** @description JSON string of recommended actions */
            actionItems?: string;
            /** @description Overall mood assessment */
            moodAssessment?: string | null;
            /** @description Progress tracking notes */
            progressNotes?: string | null;
            /**
             * Format: date-time
             * @description Report generation timestamp
             */
            createdAt?: string;
        };
        ModelConfig: {
            /**
             * @description Model identifier used in API calls
             * @example openai/gpt-oss-120b
             */
            id: string;
            /**
             * @description Human-readable model name
             * @example GPT OSS 120B
             */
            name: string;
            /**
             * @description Model provider/company
             * @example OpenAI
             */
            provider: string;
            /**
             * @description Maximum tokens supported by the model
             * @example 32000
             */
            maxTokens: number;
            /**
             * @description Model category/stability level
             * @example featured
             * @enum {string}
             */
            category: "featured" | "production" | "preview";
        };
        ChatRequest: {
            /** @description Array of conversation messages */
            messages: {
                /** @enum {string} */
                role?: "user" | "assistant";
                content?: string;
            }[];
            /**
             * Format: uuid
             * @description Optional session ID for context
             */
            sessionId?: string;
            /**
             * @description AI model to use
             * @example openai/gpt-oss-120b
             */
            model?: string;
            /** @description Groq API key (if not set in environment) */
            apiKey?: string;
            /**
             * @description Response creativity (0=focused, 2=creative)
             * @example 0.7
             */
            temperature?: number;
            /**
             * @description Maximum response length
             * @example 2000
             */
            maxTokens?: number;
            /**
             * @description Nucleus sampling parameter
             * @example 0.9
             */
            topP?: number;
        };
        CreateSessionRequest: {
            /**
             * @description Session title
             * @example Managing Anxiety and Stress
             */
            title: string;
        };
        EmailReportRequest: {
            /**
             * Format: uuid
             * @description Session to generate report for
             */
            sessionId: string;
            /** @description Session messages */
            messages: components["schemas"]["Message"][];
            /**
             * Format: email
             * @description Recipient email address
             * @example user@example.com
             */
            emailAddress: string;
            /**
             * @description AI model for report generation
             * @example openai/gpt-oss-120b
             */
            model?: string;
            emailConfig?: {
                /**
                 * @description Email service type
                 * @enum {string}
                 */
                service?: "console" | "smtp";
                /**
                 * @description SMTP server hostname
                 * @example smtp.gmail.com
                 */
                smtpHost?: string;
                /**
                 * Format: email
                 * @description SMTP username
                 */
                smtpUser?: string;
                /** @description SMTP password or app password */
                smtpPass?: string;
                /**
                 * Format: email
                 * @description Sender email address
                 */
                fromEmail?: string;
            };
        };
        Error: {
            /**
             * @description Error message
             * @example Validation failed
             */
            error: string;
            /**
             * @description Detailed error information
             * @example Invalid email address format
             */
            details?: string;
            /**
             * @description Error code for programmatic handling
             * @example VALIDATION_ERROR
             */
            code?: string;
            /**
             * @description Suggested action to resolve the error
             * @example Please check your input and try again
             */
            suggestedAction?: string;
        };
    };
    responses: {
        /** @description Bad request - invalid input */
        BadRequest: {
            headers: {
                /** @description Correlation ID for tracing this request */
                "X-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                /** @description Correlation ID for tracing this request */
                "X-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Correlation ID for tracing this request */
        "X-Request-Id": string;
        /** @description Model identifier used to generate the response */
        "X-Model-Id": string;
        /** @description Tool choice directive for the model (e.g., required/none) */
        "X-Tool-Choice": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
